name: publish to nuget

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.0.4
        with:
          PROJECT_FILE_PATH: src/FlareSolverrSharp/FlareSolverrSharp.csproj
          
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
